/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.event.KeyEvent;
import javax.swing.KeyStroke;

/**
 *
 * @author Nahuel
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    static final String SUMA = "SUMA";
    static final String RESTA = "RESTA";
    static final String DIVISION = "DIVISION";
    static final String MULTIPLICACION = "MULTIPLICACION";
    static final String IGUAL = "IGUAL";
    static final String PRIMERA = "PRIMERA";

    private Operacion operacion = new Operacion();
    private boolean displayResultado = false;
    private String ultimaOperacion = "";
    private static final VentanaCalculadora ventanaCalculadoraUnica = new VentanaCalculadora();

    /**
     * Creates new form VentanaCalculadora
     */
    public static VentanaCalculadora getVentanaCalculadora() {
        return ventanaCalculadoraUnica;
    }

    private VentanaCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle("Calculadora");
        this.ultimaOperacion = "PRIMERA";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visor = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        buttonCE = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonBackspace = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonNegate = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonComa = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        leyendaOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visor.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });
        visor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                visorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                visorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                visorKeyTyped(evt);
            }
        });

        buttonsPanel.setLayout(new java.awt.GridLayout(5, 0, 5, 5));

        buttonCE.setBackground(new java.awt.Color(153, 255, 255));
        buttonCE.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonCE.setText("CE");
        buttonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCEActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonCE);

        buttonC.setBackground(new java.awt.Color(153, 255, 255));
        buttonC.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonC);

        buttonBackspace.setBackground(new java.awt.Color(153, 255, 255));
        buttonBackspace.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonBackspace.setText("Backspace");
        buttonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackspaceActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonBackspace);

        buttonDivide.setBackground(new java.awt.Color(153, 255, 255));
        buttonDivide.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonDivide.setText("÷");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonDivide);

        button7.setBackground(new java.awt.Color(204, 204, 204));
        button7.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button7);

        button8.setBackground(new java.awt.Color(204, 204, 204));
        button8.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button8);

        button9.setBackground(new java.awt.Color(204, 204, 204));
        button9.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button9);

        buttonMultiply.setBackground(new java.awt.Color(153, 255, 255));
        buttonMultiply.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonMultiply.setText("x");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonMultiply);

        button4.setBackground(new java.awt.Color(204, 204, 204));
        button4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button4);

        button5.setBackground(new java.awt.Color(204, 204, 204));
        button5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button5);

        button6.setBackground(new java.awt.Color(204, 204, 204));
        button6.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button6);

        buttonMinus.setBackground(new java.awt.Color(153, 255, 255));
        buttonMinus.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonMinus);

        button1.setBackground(new java.awt.Color(204, 204, 204));
        button1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button1);

        button2.setBackground(new java.awt.Color(204, 204, 204));
        button2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button2);

        button3.setBackground(new java.awt.Color(204, 204, 204));
        button3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button3);

        buttonPlus.setBackground(new java.awt.Color(153, 255, 255));
        buttonPlus.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonPlus);

        buttonNegate.setBackground(new java.awt.Color(153, 255, 255));
        buttonNegate.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonNegate.setText("±");
        buttonNegate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegateActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonNegate);

        button0.setBackground(new java.awt.Color(204, 204, 204));
        button0.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button0);

        buttonComa.setBackground(new java.awt.Color(153, 255, 255));
        buttonComa.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonComa.setText(".");
        buttonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComaActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonComa);

        buttonEquals.setBackground(new java.awt.Color(153, 255, 255));
        buttonEquals.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonEquals);

        leyendaOperacion.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        leyendaOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leyendaOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leyendaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "2");
    }//GEN-LAST:event_button2ActionPerformed

    private void visorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visorKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if (!this.isCharacterAcceptable(vchar)
                || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (((vchar == ',') || (vchar == '.')) && (this.hayMasDeUno(this.visor.getText(), Character.toString(vchar)))) {
            evt.consume();
        }
    }//GEN-LAST:event_visorKeyTyped

    private void buttonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackspaceActionPerformed
        // TODO add your handling code here:
        if (this.visor.getText().length() > 0) {
            this.visor.setText(this.visor.getText().substring(0, this.visor.getText().length() - 1));
        }
    }//GEN-LAST:event_buttonBackspaceActionPerformed

    private void buttonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComaActionPerformed
        // TODO add your handling code here:
        if (!(this.visor.getText().contains("."))) {
            this.visor.setText(this.visor.getText() + ".");
        }
    }//GEN-LAST:event_buttonComaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "1");
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
//            System.out.println(this.visor.getText()+" "+this.displayResultado);
            this.displayResultado = false;
//            System.out.println(this.visor.getText()+" "+this.displayResultado);
        }
        this.visor.setText(this.visor.getText() + "3");

    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "4");
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "5");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "6");
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "7");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "8");
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "9");
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        if (this.displayResultado == true) {
            this.visor.setText("");
            this.displayResultado = false;
        }
        this.visor.setText(this.visor.getText() + "0");
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonNegateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegateActionPerformed
        // TODO add your handling code here:
        if (this.visor.getText().startsWith("-")) {
            this.visor.setText(this.visor.getText().substring(1));
        } else {
            this.visor.setText("-".concat(this.visor.getText()));
        }
    }//GEN-LAST:event_buttonNegateActionPerformed

    private void buttonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCEActionPerformed
        // TODO add your handling code here:
        this.visor.setText("");
        this.ultimaOperacion = "PRIMERA";
    }//GEN-LAST:event_buttonCEActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        // TODO add your handling code here:
        if (this.ultimaOperacion.equals(PRIMERA) || this.ultimaOperacion.equals(IGUAL)) {
            operacion.cargarOperando1(this.visor.getText());
        } else {
            this.visor.setText(String.valueOf(operacion.igual(this.visor.getText(), this.ultimaOperacion)));
        }
//        this.displayResultado = true;
//        this.ultimaOperacion = SUMA;
//        this.leyendaOperacion.setText(operacion.getLeyenda_operacion());
//        System.out.println(operacion.getLeyenda_operacion() + "=" + this.visor.getText());
        this.finalizarOperacion(SUMA);

    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        // TODO add your handling code here:
        operacion = new Operacion();
        this.visor.setText("");
        this.leyendaOperacion.setText("");
        this.ultimaOperacion = PRIMERA;
        this.displayResultado = false;
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
        this.visor.setText(String.valueOf(operacion.igual(this.visor.getText(), this.ultimaOperacion)));
//        System.out.println(operacion.getLeyenda_operacion() + "=" + this.visor.getText());
//        this.displayResultado = true;
//        this.ultimaOperacion = IGUAL;
//        this.leyendaOperacion.setText(operacion.getLeyenda_operacion());
        this.finalizarOperacion(IGUAL);
        operacion = new Operacion();
    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        if (this.ultimaOperacion.equals(PRIMERA) || this.ultimaOperacion.equals(IGUAL)) {
            operacion.cargarOperando1(this.visor.getText());
        } else {
            this.visor.setText(String.valueOf(operacion.igual(this.visor.getText(), this.ultimaOperacion)));
        }
//        this.displayResultado = true;
//        this.ultimaOperacion = RESTA;
//        this.leyendaOperacion.setText(operacion.getLeyenda_operacion());
//        System.out.println(operacion.getLeyenda_operacion() + "=" + this.visor.getText());
        this.finalizarOperacion(RESTA);
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        // TODO add your handling code here:
        if (this.ultimaOperacion.equals(PRIMERA) || this.ultimaOperacion.equals(IGUAL)) {
            operacion.cargarOperando1(this.visor.getText());
        } else {
            this.visor.setText(String.valueOf(operacion.igual(this.visor.getText(), this.ultimaOperacion)));

        }
//        this.displayResultado = true;
//        this.ultimaOperacion = MULTIPLICACION;
//        this.leyendaOperacion.setText(operacion.getLeyenda_operacion());
//        System.out.println(operacion.getLeyenda_operacion() + "=" + this.visor.getText());
        this.finalizarOperacion(MULTIPLICACION);

    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        // TODO add your handling code here:
        if (this.ultimaOperacion.equals(PRIMERA) || this.ultimaOperacion.equals(IGUAL)) {
            operacion.cargarOperando1(this.visor.getText());
        } else {
            this.visor.setText(String.valueOf(operacion.igual(this.visor.getText(), this.ultimaOperacion)));
        }
//        this.displayResultado = true;
//        this.ultimaOperacion = DIVISION;
//        this.leyendaOperacion.setText(operacion.getLeyenda_operacion());
//        System.out.println(operacion.getLeyenda_operacion() + "=" + this.visor.getText());
        this.finalizarOperacion(DIVISION);
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void visorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visorKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_visorKeyPressed

    private void visorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visorKeyReleased
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if ((vchar == '.') && (this.visor.getText().startsWith("."))) {
            this.visor.setText("0.");
    }//GEN-LAST:event_visorKeyReleased
    }

    private boolean isCharacterAcceptable(char vchar) {
        return ((Character.isDigit(vchar)) || (vchar == ('.')));
    }

    private void finalizarOperacion(String tipoOperacion) {
        this.displayResultado = true;
        this.ultimaOperacion = tipoOperacion;
        this.leyendaOperacion.setText(operacion.getLeyenda_operacion());
        System.out.println(operacion.getLeyenda_operacion() + "=" + this.visor.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    private boolean hayMasDeUno(String cadenaARevisar, String subcadenaARevisar) {
        String str = cadenaARevisar;
        String findStr = subcadenaARevisar;
        int lastIndex = 0;
        int count = 0;

        while (lastIndex != -1) {
            lastIndex = str.indexOf(findStr, lastIndex);
            if (lastIndex != -1) {
                count++;
                lastIndex += findStr.length();
            }
        }
//        System.out.println(count);
        return count >= 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonBackspace;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonCE;
    private javax.swing.JButton buttonComa;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNegate;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel leyendaOperacion;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
